[Task1]
DynamicVariables=1
MeterStyle=style.task.exe | Task1.actions
X=0
Meter=String
MeasureName=MeasureTask1exe
Group=Task1Group | TaskGroup

[Task2]
DynamicVariables=1
MeterStyle=style.task.exe | Task2.actions
Meter=String
MeasureName=MeasureTask2exe
Group=Task2Group | TaskGroup

[Task3]
DynamicVariables=1
MeterStyle=style.task.exe | Task3.actions
Meter=String
MeasureName=MeasureTask3exe
Group=Task3Group | TaskGroup

[Task4]
DynamicVariables=1
MeterStyle=style.task.exe | Task4.actions
Meter=String
MeasureName=MeasureTask4exe
Group=Task4Group | TaskGroup

[Task5]
DynamicVariables=1
MeterStyle=style.task.exe | Task5.actions
Meter=String
MeasureName=MeasureTask5exe
Group=Task5Group | TaskGroup

[Task6]
DynamicVariables=1
MeterStyle=style.task.exe | Task6.actions
Meter=String
MeasureName=MeasureTask6exe
Group=Task6Group | TaskGroup

[Task7]
DynamicVariables=1
MeterStyle=style.task.exe | Task7.actions
Meter=String
MeasureName=MeasureTask7exe
Group=Task7Group | TaskGroup

[Task8]
DynamicVariables=1
MeterStyle=style.task.exe | Task8.actions
Meter=String
MeasureName=MeasureTask8exe
Group=Task8Group | TaskGroup

[Task9]
DynamicVariables=1
MeterStyle=style.task.exe | Task9.actions
Meter=String
MeasureName=MeasureTask9exe
Group=Task9Group | TaskGroup

[Task10]
DynamicVariables=1
MeterStyle=style.task.exe | task10.actions
Meter=String
MeasureName=MeasureTask10exe
Group=Task10Group | TaskGroup

[Task11]
DynamicVariables=1
MeterStyle=style.task.exe | task11.actions
Meter=String
MeasureName=MeasureTask11exe
Group=Task11Group | TaskGroup

[Task12]
DynamicVariables=1
MeterStyle=style.task.exe | task12.actions
Meter=String
MeasureName=MeasureTask12exe
Group=Task12Group | TaskGroup

[Task13]
DynamicVariables=1
MeterStyle=style.task.exe | task13.actions
Meter=String
MeasureName=MeasureTask13exe
Group=Task13Group | TaskGroup

[Task14]
DynamicVariables=1
MeterStyle=style.task.exe | task14.actions
Meter=String
MeasureName=MeasureTask14exe
Group=Task14Group | TaskGroup

[Task15]
DynamicVariables=1
MeterStyle=style.task.exe | task15.actions
Meter=String
MeasureName=MeasureTask15exe
Group=Task15Group | TaskGroup

[Task16]
DynamicVariables=1
MeterStyle=style.task.exe | task16.actions
Meter=String
MeasureName=MeasureTask16exe
Group=Task16Group | TaskGroup