[Tray1]
DynamicVariables=1
MeterStyle=style.tray.exe | tray1.actions
Meter=String
X=0
MeasureName=MeasureTray1exe
Group=Tray1Group | TrayGroup

[Tray2]
DynamicVariables=1
MeterStyle=style.tray.exe | tray2.actions
Meter=String
MeasureName=MeasureTray2exe
Group=Tray2Group | TrayGroup

[Tray3]
DynamicVariables=1
MeterStyle=style.tray.exe | tray3.actions
Meter=String
MeasureName=MeasureTray3exe
Group=Tray3Group | TrayGroup

[Tray4]
DynamicVariables=1
MeterStyle=style.tray.exe | tray4.actions
Meter=String
MeasureName=MeasureTray4exe
Group=Tray4Group | TrayGroup

[Tray5]
DynamicVariables=1
MeterStyle=style.tray.exe | tray5.actions
Meter=String
MeasureName=MeasureTray5exe
Group=Tray5Group | TrayGroup

[Tray6]
DynamicVariables=1
MeterStyle=style.tray.exe | tray6.actions
Meter=String
MeasureName=MeasureTray6exe
Group=Tray6Group | TrayGroup

[Tray7]
DynamicVariables=1
MeterStyle=style.tray.exe | tray7.actions
Meter=String
MeasureName=MeasureTray7exe
Group=Tray7Group | TrayGroup

[Tray8]
DynamicVariables=1
MeterStyle=style.tray.exe | tray8.actions
Meter=String
MeasureName=MeasureTray8exe
Group=Tray8Group | TrayGroup

[Tray9]
DynamicVariables=1
MeterStyle=style.tray.exe | tray9.actions
Meter=String
MeasureName=MeasureTray9exe
Group=Tray9Group | TrayGroup

[Tray10]
DynamicVariables=1
MeterStyle=style.tray.exe | tray10.actions
Meter=String
MeasureName=MeasureTray10exe
Group=Tray10Group | TrayGroup